# Default values for yurt-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# settings for log print
log:
  # log level for yurt-manager
  level: 4

replicaCount: 1
nameOverride: ""

image:
  registry: openyurt
  repository: yurt-manager
  tag: v1.4.0
  pullSecrets: []
  # pullSecrets:
  #   - name: myRegistryKeySecretName

ports:
  metrics: 10271
  healthProbe: 10272
  webhook: 10273

# format should be "foo,-bar,*"
controllers: "*"

# format should be "foo,*"
disableIndependentWebhooks: ""

leaderElectResourceName: "cloud-yurt-manager"

# resources of yurt-manager container
resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
