# Default values for yurthub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""

cacheAgents: ""

yurthubBindingAddr: 127.0.0.1
kubernetesServerAddr: https://127.0.0.1:6443
bootstrapFile: "/var/lib/yurthub/bootstrap-hub.conf"
organizations: ""
nodePoolName: ""

image:
  registry: openyurt
  repository: yurthub
  tag: ""