# Default values for yurthub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""

cacheAgents: ""

bootstrapFile: "/var/lib/yurthub/bootstrap-hub.conf"

image:
  registry: openyurt
  repository: yurthub
  tag: latest