apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: yurtappoverriders.apps.openyurt.io
spec:
  group: apps.openyurt.io
  names:
    kind: YurtAppOverrider
    listKind: YurtAppOverriderList
    plural: yurtappoverriders
    shortNames:
    - yacr
    singular: yurtappoverrider
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The subject kind of this overrider.
      jsonPath: .subject.kind
      name: Subject
      type: string
    - description: CreationTimestamp is a timestamp representing the server time when
        this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC.
      jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          entries:
            items:
              description: Describe detailed multi-region configuration of the subject
                Entry describe a set of nodepools and their shared or identical configurations
              properties:
                items:
                  items:
                    description: Item represents configuration to be injected. Only
                      one of its members may be specified.
                    properties:
                      image:
                        description: ImageItem specifies the corresponding container
                          and the claimed image
                        properties:
                          containerName:
                            description: ContainerName represents name of the container
                              in which the Image will be replaced
                            type: string
                          imageClaim:
                            description: ImageClaim represents the claimed image name
                              which is injected into the container above
                            type: string
                        required:
                        - containerName
                        - imageClaim
                        type: object
                      replicas:
                        format: int32
                        type: integer
                    type: object
                  type: array
                patches:
                  description: Convert Patch struct into json patch operation
                  items:
                    properties:
                      operation:
                        description: type represents the operation default is strategic
                          merge patch
                        enum:
                        - add
                        - remove
                        - replace
                        type: string
                      path:
                        description: Path represents the path in the json patch
                        type: string
                      value:
                        description: Indicates the patch for the template
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - operation
                    - path
                    type: object
                  type: array
                pools:
                  items:
                    type: string
                  type: array
              required:
              - pools
              type: object
            type: array
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          subject:
            description: Describe the object Entries belongs
            properties:
              apiVersion:
                description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                type: string
              kind:
                description: 'Kind is a string value representing the REST resource
                  this object represents. Servers may infer this from the endpoint
                  the client submits requests to. Cannot be updated. In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                type: string
              name:
                description: Name is the name of YurtAppSet or YurtAppDaemon
                type: string
            required:
            - name
            type: object
        required:
        - entries
        - subject
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
