updated: false
count: 6
latestVersion: minnesota
versions:
- name: kamakura
  requiredComponents: 
  - edgex-core-command
  - edgex-core-consul
  - edgex-core-metadata
  - edgex-redis
- name: jakarta
  requiredComponents: 
  - edgex-core-command
  - edgex-core-consul
  - edgex-core-metadata
  - edgex-redis
- name: levski
  requiredComponents: 
  - edgex-core-command
  - edgex-core-consul
  - edgex-core-metadata
  - edgex-redis
- name: minnesota
  requiredComponents: 
  - edgex-core-command
  - edgex-core-consul
  - edgex-core-metadata
  - edgex-redis
- name: ireland
  requiredComponents: 
  - edgex-core-command
  - edgex-core-consul
  - edgex-core-metadata
  - edgex-redis
- name: hanoi
  requiredComponents: 
  - edgex-core-command
  - edgex-core-consul
  - edgex-core-metadata
  - edgex-redis
