apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: __project_prefix__-tunnel-agent
  name: __project_prefix__-tunnel-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: __project_prefix__-tunnel-agent
  template:
    metadata:
      labels:
        k8s-app: __project_prefix__-tunnel-agent
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        __label_prefix__/is-edge-worker: "true"
      containers:
      - command:
        - __project_prefix__-tunnel-agent
        args:
        - --node-name=$(NODE_NAME)
        - --node-ip=$(POD_IP)
        - --v=2
        image: __repo__/__project_prefix__-tunnel-agent:__tag__
        imagePullPolicy: IfNotPresent
        name: __project_prefix__-tunnel-agent
        volumeMounts:
        - name: k8s-dir
          mountPath: /etc/kubernetes
        - name: kubelet-pki
          mountPath: /var/lib/kubelet/pki
        - name: tunnel-agent-dir
          mountPath: /var/lib/yurttunnel-agent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      hostNetwork: true
      restartPolicy: Always
      tolerations:
        - operator: Exists
      volumes:
      - name: k8s-dir
        hostPath:
          path: /etc/kubernetes
          type: Directory
      - name: kubelet-pki
        hostPath:
          path: /var/lib/kubelet/pki
          type: Directory
      - name: tunnel-agent-dir
        hostPath:
          path: /var/lib/yurttunnel-agent
          type: DirectoryOrCreate
