apiVersion: apps.openyurt.io/v1alpha1
kind: StaticPod
metadata:
  name: yurt-hub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yurthub.labels" . | nindent 4 }}
spec:
  staticPodManifest: yurthub
  template:
    metadata:
      labels:
        k8s-app: yurt-hub
      name: yurt-hub
      namespace: {{ .Release.Namespace }}
    spec:
      volumes:
        - name: hub-dir
          hostPath:
            path: /var/lib/yurthub
            type: DirectoryOrCreate
        - name: kubernetes
          hostPath:
            path: /etc/kubernetes
            type: Directory
      containers:
        - name: yurt-hub
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: hub-dir
              mountPath: /var/lib/yurthub
            - name: kubernetes
              mountPath: /etc/kubernetes
          command:
            - yurthub
            - --v=2
            - --bind-address={{`{{.yurthubBindingAddr}}`}}
            - --server-addr={{`{{.kubernetesServerAddr}}`}}
            - --node-name=$(NODE_NAME)
            - --bootstrap-file={{ .Values.bootstrapFile }}
            - --working-mode={{`{{.workingMode}}`}}
            - --namespace={{ .Release.Namespace }}
              {{`{{if .organizations }}`}}
            - --hub-cert-organizations={{`{{.organizations}}`}}
              {{`{{end}}`}}
          livenessProbe:
            httpGet:
              host: {{`{{.yurthubBindingAddr}}`}}
              path: /v1/healthz
              port: 10267
            initialDelaySeconds: 300
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 150Mi
            limits:
              memory: 300Mi
          securityContext:
            capabilities:
              add: [ "NET_ADMIN", "NET_RAW" ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      hostNetwork: true
      priorityClassName: system-node-critical
      priority: 2000001000


