name: Sync Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  sync-charts:
    if: github.repository == 'openyurtio/openyurt'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to openyurtio/charts Repo
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SYNC_OPENYURTIO_CHARTS_KEY }}
          COMMIT_ID: ${{ github.sha }}
        run: |
          bash ./hack/lib/sync-charts.sh
